<?php
include_once 'CurlBlogClient.php';
/**
 * Created by PhpStorm.
 * User: HP PC
 * Date: 12/11/2016
 * Time: 11:37 PM
 */
class PersianBlogClient extends CurlBlogClient
{
    /**
     * PersianBlogClient constructor.
     * @param $username The user name for persian blog account
     * @param $password The password for persian blog account
     * @param null $blog_tag Blog specifier
     */
    public function __construct($username, $password, $blog_tag = null)
    {
        parent::__construct(array(
            'TxtPassword' => $password,
            'TxtUsername' => $username
        ), "http://persianblog.ir/Login.aspx?ReturnUrl=%2fHome.aspx", $blog_tag);
    }
    /**
     * @param null $blog_tag The blog ID, you can find it in the url while posting to a blog
     * @param $title The title for the post
     * @param $body The body
     */
    public function send_post($title, $body, $blog_tag = null){
        if ($blog_tag != null)
            $this->blog_tag = $blog_tag;
        parent::post(array('TxtTitle' => $title, 'intrContent' => $body));
    }
    /**
     * @return mixed returns url to post to weblog
     */
    protected function get_post_url()
    {
        // try to load posting page
        $ch = $this->grab_page_handle("http://persianblog.ir/CreatePost.aspx?blogID=$this->blog_tag");
        // get the redirected url containing the 'h' parameter
        $last_url = curl_getinfo($ch, CURLINFO_REDIRECT_URL);
        return $last_url;
    }

    protected function get_form_action($html)
    {
        return 'http://persianblog.ir/'.parent::get_form_action($html); // TODO: Change the autogenerated stub
    }


}